[package]
name = "QR-Code-Gen-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
glib = "0.19.9"
qrcode = "0.14.1"
image = "0.25.1"
chrono = "0.4"